USE MagicWallet
GO
CREATE TABLE USERS (
	UserID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	UserName VARCHAR(255) NOT NULL,
	UserPWD VARCHAR(64) NOT NULL,
	Balance BIGINT NOT NULL DEFAULT 0
);
CREATE TABLE TRANSACTIONS (
	TID INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	UserFROM INT NOT NULL FOREIGN KEY REFERENCES USERS(UserID),
	UserTO INT NOT NULL FOREIGN KEY REFERENCES USERS(UserID),
	TAmount BIGINT NOT NULL,
	TDateTime DATETIME NOT NULL,
	THash VARCHAR(64) NOT NULL,
);